name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        # Before submitting any bug report, make sure that you can reproduce the issue on latest dev branch
        https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: browsers
    validations:
      required: true
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: stacktracke
    attributes:
      label: Relevant stacktrace
      render: shell
  - type: dropdown
    id: initial_state
    validations:
      required: true
    attributes:
      label: Did you download state.json.zip?
      description: The file from error page (blinking link) or `Zigbee2MQTT frontend -> Settings -> Tools -> Download state`.<br> [How to attach file](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files)<br>**NOT** `data/state.json` from zigbee2mqtt folder
      multiple: false
      options:
        - I will attach state.json.zip
        - I will not attach state.json.zip
