// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const node: string;
export const link: string;
export const label: string;
export const Coordinator: string;
export const coordinator: string;
export const labels: string;
export const links: string;
export const nodes: string;
export const EndDevice: string;
export const endDevice: string;
export const Router: string;
export const router: string;
